### ISSUE TITLE
Request: Make manual mode selection possible

### ISSUE THREAD

**Issue by ghost** [bmatcuk/flipperzero-qrcode#2]
Hi,
I actually want to make a request rather than a complaint, because in some cases I have had problems with the app choosing the QR display mode automatically.
I have some shop membership cards (point collection cards, often shared with other family members) with relatively short (12 chars max.) numeric IDs which are not encoded as purely numeric, but in alphanumeric mode. And the payment terminals (I guess deliberately) only accept that display format (also with one specific ECC) when scanned.
It would be nice to be able to carry those with Me on My Flipper Zero like I already do with many other useful stuff.
I do recognise some limitations are necessary for the display modes of QR codes do to the limited display size and resolution of Flipper Zero. But it would be nice to at least have the option to manually change the display mode of codes up to a predetermined character length. (Say 18-20 charachers...)  This would make it possible to resolve problems like I am having currently.
Hope You will consider...
THX

**Comment by Himura2la** [comment]
Please, also allow specifying the default version, because most qr codes I tested were detected as EAN-8 or UPC-E by [my reader](https://github.com/wewewe718/QrAndBarcodeScanner), another readers also worked bad on them (e.g. Firefox Mobile). Raising the version made them much more readable.

**Comment by ghost** [comment]
@Himura2la Multiple factors are influencing the readability and reading accuracy of QR codes. But most of the problems araise from the hardvare and software used to read them.
I also tried/used many apps and various QR/barcode scanning devices for years now and I have to say, most of them are simply garbage.
Lets just say it requires a slightly more sophisticated scanner and algorithms to be able to read a QR code or barcode displayed on the Flipper Zeros display than the ones used to read the same from a plain white paper, printed in large size.
And honestly, I still don't have one specific app I could recommend that could do any and all 2D codes with 100% accuracy. Because even if the software is perfect, there's always the question mark on the other side of the equation: How good is the hardvare You use to scan the code? :/
Please note that QR is a standard using strict, unified parameters. So the fact that your app recognises a QR as an EAN-8 or UPC-E barcode... Well, that says a lot, because that's a huge BUG(!). XD I think You should definitely try an other one...
For example, Google Lens does a pretty decent job identifying and reading 2D codes - among other things...

**Comment by Himura2la** [comment]
@V-kond, This message is offtopic, I know well everything you talk about, and I noticed that increasing QR version by one from it's minimum drastically improves readability. So I simply ask about an ability to configure all QR code parameters in the file, not only it's type but also version and ECC.

My scanner detects 1D codes because there's no way to specify which code to read, and some part of the QR code displaied on Flipper can be read as a valid barcode. Barcode is simply easier to find by the scanner than the QR-code. This is not a bug, this means that it's in possible to display a QR code on Flipper and fully follow the standard. My guess is that gaps between pixels are making some parts of QR-codes look like 1D codes.

**Comment by bmatcuk** [comment]
Sorry it took so long to get to this. I built this app in, basically, a weekend and then got busy with other things. I have finally found some free time to address feature requests for this app! The reason I didn't originally support this is because the library I was using to build the qrcodes didn't support it. But it turned out to be fairly easy to hack in.
